version: "3"
services:
  web:
    container_name: web
    env_file:
      - web/.env
    environment:
      - CMS_API=http://cms:1337/api
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - ./web/src:/app/src
    ports:
      - 3000:3000
    networks:
      - vim_network

  db:
    container_name: db
    restart: unless-stopped
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${CMS_DATABASE_NAME}
    volumes:
      - vim-cms-data:/var/lib/mysql
      - ./db/docker-scripts:/docker-entrypoint-initdb.d
    ports:
      - ${DATABASE_PORT}:3306
    networks:
      - vim_network

  cms:
    container_name: strapi
    build:
      context: ./cms
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./cms/.env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${CMS_DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${CMS_JWT_SECRET}
      ADMIN_JWT_SECRET: ${CMS_ADMIN_JWT_SECRET}
      APP_KEYS: ${CMS_APP_KEYS}
      NODE_ENV: ${NODE_ENV}
      STRAPI_DISABLE_UPDATE_NOTIFICATION: false
      STRAPI_TELEMETRY_DISABLED: true
    volumes:
      - ./cms/config:/opt/app/config
      - ./cms/src:/opt/app/src
      - ./cms/package.json:/opt/package.json
      - ./cms/.env:/opt/app/.env
      - ./cms/public/uploads:/opt/app/public/uploads
    ports:
      - 1337:1337
    networks:
      - vim_network
    depends_on:
      - db

volumes:
  vim-cms-data:

networks:
  vim_network:
    name: vim_network
    driver: bridge
