import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import '../styles/globals.scss';
import qs from 'qs';
import Layout from '@/components/Layout/Layout';

const params = {
    nested: true,
    populate: {
        items: {
            populate: {
                page_relation: true,
            },
        },
    },
};

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Vim Landing Page',
    description: 'Generated by create next app',
};

async function getPageProps() {
    const query = qs.stringify(params, { addQueryPrefix: true });
    const respose = await fetch(`${process.env.CMS_API}/menus/1${query}`, {
        // headers: {
        //     authorization: `Bearer ${process.env.CMS_TOKEN}`,
        // },
    });
    
    const jsonData = await respose.json();
    console.log("This is the layout: ", jsonData.data)
    return jsonData.data.attributes.items.data;
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const pageProps = await getPageProps();

    return (
        <html lang="en">
            <body className={inter.className}>
                <Layout pages={pageProps}>{children}</Layout>
            </body>
        </html>
    );
}
