import { Fira_Code } from "next/font/google";
import { getServerSession } from "next-auth";
import type { Metadata } from "next";
import "../styles/globals.scss";
import qs from "qs";
import Layout from "@/components/Layout/Layout";
import SessionProvider from "./../components/SessionProvider";

const params = {
	nested: true,
	populate: {
		items: {
			populate: {
				page_relation: true,
			},
		},
	},
};

const firaCode = Fira_Code({ subsets: ["latin"], display: "swap", variable: "--font-fira" });

export const metadata: Metadata = {
	title: "Vim Landing Page",
	description: "Generated by create next app",
};

async function getPageProps() {
	const query = qs.stringify(params, { addQueryPrefix: true });

	try {
		const response = await fetch(`${process.env.CMS_API}/menus/1${query}`, {
			// headers: {
			//     authorization: `Bearer ${process.env.CMS_TOKEN}`,
			// },
		});

		return (await response.json()).data.attributes.items.data;
	} catch (error) {
		return [];
	}
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const pageProps = await getPageProps();
	const session = await getServerSession();

	return (
		<SessionProvider session={session}>
			<html lang="en">
				<body className={firaCode.className}>{pageProps && <Layout pages={pageProps}>{children}</Layout>}</body>
			</html>
		</SessionProvider>
	);
}
