import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import '../styles/globals.scss';
import Layout from '@/components/Layout/Layout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Vim Landing Page',
    description: 'Generated by create next app',
};

async function getPageProps() {
    const respose = await fetch(`${process.env.CMS_API}/pages`, {
        // headers: {
        //     authorization: `Bearer ${process.env.CMS_TOKEN}`,
        // },
    });
    return (await respose.json()).data;
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const pageProps = await getPageProps();

    return (
        <html lang="en">
            <body className={inter.className}>
                <Layout pages={pageProps}>{children}</Layout>
            </body>
        </html>
    );
}
